### ISSUE TITLE
InvalidCastException when deserializing objects from JSON

### ISSUE THREAD

**Issue by howcheng** [scale-tone/linq2dynamodb#29]
In a number of places, such as EntityKey, you have lines like this:

`this.HashKey = ((CachePrimitiveWrapper) en.Value).Primitive;`

However, when the object is serialized to JSON (in my case, using Newtonsoft.Json.JsonConvert), you get an InvalidCastException because you can't cast a JObject back to a CachePrimitiveWrapper.

(Note that I'm implementing your ITableCache interface for use with Elasticache/Redis.)

**Comment by scale-tone** [comment]
Hi Howard,

That's cool idea - to implement ITableCache for Redis. But why using Newtonsoft.Json for that?

You could use binary serialization instead, which is already implemented for cached objects (via CacheDocumentWrapper etc.). With helper function like this:

`public static byte[] ToByteArray(this Document doc)
{
    using (var memoryStream = new MemoryStream())
    {
        new BinaryFormatter().Serialize(memoryStream, new CacheDocumentWrapper(doc));
        return memoryStream.ToArray();
    }
}
`

and then:

`redisDatabase.StringSet(key, myDocument.ToByteArray());`

Binary serialization is much faster, than string serialization with Newtonsoft.Json. And StackExchange.Redis supports storing/retrieving byte arrays.

**Comment by howcheng** [comment]
Yeah, eventually I switched to binary serialization. I tend to like string serialization just because it's human readable when debugging.
