### ISSUE TITLE
SubmitChanges is changing NS to SS

### ISSUE THREAD

**Issue by calabresechris** [scale-tone/linq2dynamodb#37]
Hey all. First off, I love this project and I'll hopefully be contributing in the near future. I just want to bring this up here because I submit it as a bug (in case the problem is user error):

I have a user table object with, amongst other things, a list of longs, defined as:

```
[DynamoDBProperty]
public List<long> events_attending { get; set; }
```

When using the method for updating specified in this documentation, I did this:

```
userEntry = usersTable.Where(u => u.id == user_id).Single();
userEntry.friends.Add(new FacebookUser.Friend { id = friend_id, name = friend_name });

// No changes to userEntry.events_attending being made.
ctx.SubmitChanges();
```

The modification works perfectly, however, the contents of the events_attending field are going from: 

```
"events_attending": {
  "NS" : [
     "158224",
     "143600"
   ]
}
```

to:

```
"events_attending": {
  "SS" : [
      "143600",
      "158224"     
   ]
}
```

I checked the userEntry object in debug right before called SubmitChanges and both values are still longs and events_attending is still List<long>.

What could be causing this? I dont want the NS to be changing to a SS.

Thanks in advance,
Chris

**Comment by scale-tone** [comment]
Hi Chris,

I'm afraid, this thing is as designed. Linq2DynamoDB [converts arrays and lists to PrimitiveLists](https://github.com/scale-tone/linq2dynamodb/blob/master/Sources/Linq2DynamoDb.DataContext/Utils/DynamoDbConversionUtils.cs#L247), which are in turn saved as string sets to the table.

However, you're always free to write your own IPropertyConverter for your field, if it requires special treatment.

**Comment by calabresechris** [comment]
I appreciate the response! I decided that, for now, I'm going to try and keep any collections that contain IDs as string sets. I may have to implement my own IProperty Converter for sets of integers in the future, though, so I really appreciate it.
