### ISSUE TITLE
Redis caching example

### ISSUE THREAD

**Issue by calabresechris** [scale-tone/linq2dynamodb#38]
I love that you added a library for Redis caching, however the documentation for the caching section only provides an example using Memcached. Is there any way you could add a sample of the same operation using your Redis library?

Thanks so much, 
Chris Calabrese

**Comment by scale-tone** [comment]
Sure! You just need to create an instance of [RedisTableCache](https://github.com/scale-tone/linq2dynamodb/blob/master/Sources/Linq2DynamoDb.DataContext.Caching.Redis/RedisTableCache.cs) and pass it to [DataContext.GetTable<TEntity>()](https://github.com/scale-tone/linq2dynamodb/blob/master/Sources/Linq2DynamoDb.DataContext/DataContext.cs#L99) method, in the same way as you would do with EnyimTableCache instance.

RedisTableCache constructor takes two parameters: the instance of [StackExchange.Redis.ConnectionMultiplexer](https://github.com/StackExchange/StackExchange.Redis/blob/master/StackExchange.Redis/StackExchange/Redis/ConnectionMultiplexer.cs) class (which acts as a connection to your Redis server/cluster) and the TTL for items in cache. ConnectionMultiplexer instance is usually one per process and created at application startup. Depending on your Redis cluster configuration you might need to configure ConnectionMultiplexer differently, but the simplest way - using a local Redis installation - [is shown here](https://github.com/scale-tone/linq2dynamodb/blob/master/Sources/Linq2DynamoDb.DataContext.Tests/CachingTests/RedisTableCacheTests.cs#L15).

NOTE: EnyimTableCache and RedisTableCache are NOT thread-safe, so please, don't try to reuse their instances.

**Comment by calabresechris** [comment]
Thanks! Much appreciated. I'll be doing some testing with this today!
