### ISSUE TITLE
Question re: taking sort keys into account on queries

### ISSUE THREAD

**Issue by calabresechris** [scale-tone/linq2dynamodb#39]
I can't find anything definitive about this in your documentation, so here's my question:

Do your linq queries take into account local or global secondary indices? For example, if I have 3 tables set up like this:

> table User
> userid (partition key) (unique)
> name
> 
> table Friendship
> userid (primary key)
> friendid (sort key)
> 
> table Event
> userid (primary key)
> eventid (sort key)

...would the following statement take the local secondary indicies into account and do a more-efficient query? Or would it perform a scan?

```
var friendsWithEvents = (from user in User 
  join fs in Friendship on user.userid equals friend.friendid 
  join event in Event on event.userid equals user.userid
  where fs.userid == MY_USER_ID
  select new EventFriendView
  {
    event_id = event.eventid,
    friend = new Friend { id = user.userid, name = user.name }
  });
```

Thanks for the help!

Edit: fixing some of my terminology

**Comment by scale-tone** [comment]
Hi Chris,

There're two questions here, actually:
1. Whether Global and Local Secondary indices are supported - yes, both of them are. As stated in the README, Linq2DynamoDB always [tries to choose the most effective query operation](https://github.com/scale-tone/linq2dynamodb/blob/master/Sources/Linq2DynamoDb.DataContext/TableDefinitionWrapperBase.cs#L180) and [respects secondary indices](https://github.com/scale-tone/linq2dynamodb/blob/master/Sources/Linq2DynamoDb.DataContext/TableDefinitionWrapperBase.cs#L332) (if they exist on the table). To check, what DynamoDB operation your LINQ query actually causes, simply [attach a logging handler](https://github.com/scale-tone/linq2dynamodb/blob/master/Sources/Linq2DynamoDb.DataContext/DataContext.cs#L62) to your data context. 
2. Whether you can or cannot execute that particular query. No, you cannot. Join() method is not supported so far, as [explained here](http://linq2dynamodb.codeplex.com/wikipage?title=Making%20queries). Remember: DynamoDB is not an RDBMS and not a graph database.

Hope, this makes sense.

**Comment by calabresechris** [comment]
This was super helpful. Thanks! I need to get out of the habit/mindset of using join to create the most efficient queries and realize that a foreach with a bunch of Gets is super efficiency in Dynamo.

Also, the logging thing is huge, so thanks for pointing me to that!

Chris

**Comment by calabresechris** [comment]
Hey! Me again! I'm running into a problem with a GSI not being acknowledged and I'm wondering if this is "working as intended":

I have a table "UserEvent". Hash key: user_id (string), range key: event_id (string)

I created a GSI where the hash key: event_id and range key: user_id.

This statement:

```
string event_id = "1234";
List<string> friend_ids = new List<string>{ "5678", "9876" }

myDataTable.Where(ev => ev.event_id == event_id && friend_ids.Contains(ev.id)).Select(s => s.id).ToList();

```
...is performing a scan rather than a query.

Is there any way I can force it to use the GSI that I created?

**Comment by scale-tone** [comment]
No, there's no way for that.
You're using Contains() method. Which is translated to DynamoDB's **IN** operator. Which [is only allowed for doing SCANs by DynamoDB](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Condition.html).
