### ISSUE TITLE
LessThan/GreaterThanOrEqual scan filter combination not working as intended

### ISSUE THREAD

**Issue by bvd-filigrade** [scale-tone/linq2dynamodb#45]
Using the following code on the datacontext:
```
string onOrAfter = startDate.ToString("yyyyMMddHHmmss");
string before = endDate.ToString("yyyyMMddHHmmss");
var matchingEntries = this.databaseContext.UsageEntries.Where(d => (d.Timestamp.CompareTo(onOrAfter) >= 0) && (d.Timestamp.CompareTo(before) < 0)).ToArray();
```
generates the following query debug output:  
**test-Usage : DynamoDb scan: SELECT * FROM UsageDAO WHERE Timestamp GreaterThanOrEqual 20170607124405 AND Timestamp LessThan 20170607124405**

The generated query debug output looks completely correct to me (i was testing with the same date for both values which obviously should never return results) yet I get all entries back except the entry with the given Timestamp. Timestamp is the sort key for this table and is a string field.

When I change the expression to
```
var matchingEntries = this.databaseContext.UsageEntries.Where(d => (d.Timestamp.CompareTo(onOrAfter) >= 0)).ToArray();
```
this yields debug output  
**test-Usage : DynamoDb scan: SELECT * FROM UsageDAO WHERE Timestamp GreaterThanOrEqual 20170607125753**  

everything works just fine. So does using only the LessThan operation:

Expression
```
var matchingEntries = this.databaseContext.UsageEntries.Where(d => (d.Timestamp.CompareTo(before) < 0)).ToArray();
```  
with debug output
**test-Usage : DynamoDb scan: SELECT * FROM UsageDAO WHERE Timestamp LessThan 20170607130213**

**Comment by bvd-filigrade** [comment]
A bit more testing has revealed that only the **last** condition is respected, so swapping the order in the AND operation to
```
var matchingEntries = this.databaseContext.UsageEntries.Where(d => (d.Timestamp.CompareTo(before) < 0) && (d.Timestamp.CompareTo(onOrAfter) >= 0)).ToArray();
```  
Gives me all entries that satisfy
`d.Timestamp.CompareTo(onOrAfter) >= 0`
where the other way around gave me everything before the date only.

**Comment by scale-tone** [comment]
Hi Bjorn,

Thanks for reporting this and yes, I managed to reproduce it.
From what I can see now, the issue seems to be inside **Amazon.DynamoDBv2.DocumentModel.ScanFilter.AddCondition()** method - when we add a second condition for **Timestamp** field, it just drops the first one. Probably, some kind of validation happens there, which produces such a strange result.

Will continue investigating and try to find a workaround...

**Comment by scale-tone** [comment]
Yes, the [Filter.Conditions](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/DynamoDBv2/Custom/DocumentModel/Filter.cs#L127) appeared to be a map, which means, it just doesn't support multiple conditions for a column. And doesn't throw, if someone tries to :(

The quick workaround is to use a custom [FilterExpression](https://github.com/scale-tone/linq2dynamodb/blob/master/Sources/Linq2DynamoDb.DataContext/DataContextExtensions.cs#L61).

**Comment by bvd-filigrade** [comment]
As a workaround I am currently querying only on one condition in DynamoDB and appending the second condition clientside via
`Where(firstCondition).ToArray().Where(secondCondition)`
which works but is obviously sub-optimal. It is however the simplest possible solution to the problem for me.   

I'll close the issue as this is not an issue with linq2dynamodb but with the AWSSDK.Thanks for the investigation and the suggested workaround!
