### ISSUE TITLE
Find should return null instead of throwing an exception

### ISSUE THREAD

**Issue by maynardflies** [scale-tone/linq2dynamodb#51]
The typical convention for "Find" is to return default(T) when the item doesn't exist.  In the case of Dynamo, it doesn't make sense to issue a separate query to first check if the item exists, or to throw and catch an exception for this purpose, as the item's non-existence is not an error

**Comment by scale-tone** [comment]
Added [TryFind()](https://github.com/scale-tone/linq2dynamodb/blob/master/Sources/Linq2DynamoDb.DataContext/DataTable.cs#L61) methods instead.
