### ISSUE TITLE
compatibility with .net framework <462

### ISSUE THREAD

**Issue by frodgim** [scale-tone/linq2dynamodb#53]
Hi, 

Could you please add compatibility with **.NET Frameworks 4.6.1 and 4.6** ? 
Currently, I have no way of working on these versions.

Thanks in advance. 

Regards!

**Comment by scale-tone** [comment]
For .Net Framework < 4.6.2, please, use Linq2DynamoDb.DataContext and Linq2DynamoDb.DataContext.Caching.Redis 2.0.0.

Unfortunately, there's no way to make the current code backward-compatible with old .Net Framework.

**Comment by frodgim** [comment]
If you want, I pull my request on my git local repo. The change to do is located in **Linq2DynamoDb.DataContext.csproj**:

`
    <TargetFrameworks>net46;net461;netstandard1.6</TargetFrameworks>`
