### ISSUE TITLE
compatibility backward with .NET framework 4.6 and 4.6.1 (comes from #53)

### ISSUE THREAD

**Issue by frodgim** [scale-tone/linq2dynamodb#54]
Please, I'd love if you read my last comment about this topic (closed issue  #53 ).

This change is not very complicated but it would be very helpful for anyone. I think this change it's not  impossible and it even improves this great library.

Thank you in advance,

Regards!

**Comment by scale-tone** [comment]
Hi Paco,

Just for better understanding, may I ask you what prevents you from migrating your project to .Net 4.6.2?

**Comment by frodgim** [comment]
Hi scale-tone,

We have problems with another dependencies in our enviroment. This dependencies have no possibility to upgrading to new .NET framework versions, such as >= 4.6.2. I know these are my specific requirements but I think my proposal improves the library and those changes would  even be very quickly. 

If you consider this change acceptable, I will appreciate it. 

Best regards,

**Comment by scale-tone** [comment]
OK, according to [this table](https://docs.microsoft.com/en-us/dotnet/standard/net-standard), the earliest possible .Net version is 4.6.1. I can try to compile and push packages for that version, but would it suit your needs?

**Comment by frodgim** [comment]
yes, of course.
Thanks in advance!

**Comment by scale-tone** [comment]
Hi Paco, can you please confirm that it solved your problems? So that we could close this...
