### ISSUE TITLE
OData fails when executes $select clauses

### ISSUE THREAD

**Issue by frodgim** [scale-tone/linq2dynamodb#55]
Good morning,

I can see that module OData fails when it applies any select  clause. You can test it in your Mobile Webapi sln
Concretely, it doesn't work when it try to translate the Expression for .Select.
Thanks in advance

![image](https://user-images.githubusercontent.com/1319623/32652427-8507ac0e-c604-11e7-8d6f-c84f98dd54cd.png)

**Comment by scale-tone** [comment]
Yes, $select clause isn't supported by Linq2DynamoDb.WebApi.OData.

**Comment by frodgim** [comment]
do you plan to release this feature on the roadmap?

**Comment by scale-tone** [comment]
Took a quick look. Unfortunately, it wouldn't be a 1-line change. The Select expression provided by AspNet.WebApi.OData looks quite complicated (not as simple as when you use .Select() method).
So a deeper dive is needed...

**Comment by frodgim** [comment]
Do you think about using Dynamic Linq?? Maybe this way would be easier to implement it.

Kind regards!

**Comment by scale-tone** [comment]
Sorry, took another look, and it appeared to be a trivial change in ProjectionVisitor (at least for common column types). 

Will try to publish updated packages in a few days...

**Comment by frodgim** [comment]
Thanks!!

**Comment by scale-tone** [comment]
Please, try [v2.4.0](https://www.nuget.org/packages/Linq2DynamoDb.WebApi.OData/2.4.0).
