### ISSUE TITLE
Override table name in DataContext

### ISSUE THREAD

**Issue by pvanroos** [scale-tone/linq2dynamodb#67]
@scale-tone Is there a way to override the table name when instantiating the DataContext.  I realize there's a table prefix parameter, which is great but I was looking for a table name override too.

**Comment by scale-tone** [comment]
> Is there a way to override the table name

Absolutely: https://github.com/scale-tone/linq2dynamodb/wiki/Specifying-table-name-for-an-entity

**Comment by pvanroos** [comment]
Awesome!  Thanks!
